name: Heart Disease MLOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Membangun_model/requirements.txt
          pip install mlflow dvc

      - name: Configure DVC Authentication
        run: |
          dvc remote list
          dvc remote modify --local origin auth basic
          dvc remote modify --local origin user "${{ secrets.DAGSHUB_USERNAME }}"
          dvc remote modify --local origin password "${{ secrets.DAGSHUB_TOKEN }}"

      - name: Pull Dataset from DVC
        run: |
          dvc pull

      - name: Check Dataset
        run: |
          ls -lh heart.csv
          test -f heart.csv

      - name: Run MLflow Project
        run: |
          cd Membangun_model
          mlflow run . -e train_all
